url: "https://sebdur.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/tyranno" # the subpath of your site, e.g. /blog
title: "Tyranno" # the name of your site, e.g. ACME Corp.
